const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.ScriptsInEvents.FolhaDeEventos_fase1_Event2_Act3,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.ScriptsInEvents.FolhaDeEventos_gameover_Event2_Act1,
		C3.Plugins.System.Acts.GoToLayout,
		C3.ScriptsInEvents.FolhaDeEventos_fase2_Event2_Act3,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.ScriptsInEvents.FolhaDeEventos_fase3_Event2_Act3,
		C3.Plugins.System.Cnds.OnLayoutEnd
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Piscar: 0},
	{slime: 0},
	{Teclado: 0},
	{Mouse: 0},
	{Sólido: 0},
	{Grama1_bordaesq: 0},
	{Grama2_meio: 0},
	{Grama3_bordadir: 0},
	{Espinho: 0},
	{Espinho2: 0},
	{Grama_solo: 0},
	{maca: 0},
	{Senóide: 0},
	{MoverPara: 0},
	{Inimigo_cogu: 0},
	{FonteDeSprites: 0},
	{Terra3: 0},
	{Terra1: 0},
	{Terra2: 0},
	{Terra4: 0},
	{Terra6: 0},
	{Terra5: 0},
	{FunfoGameOver: 0},
	{Áudio: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Árvore: 0},
	{Sprite4: 0},
	{BotaoTenNov: 0},
	{BotaoTelaIni: 0},
	{BotaoGameOver: 0},
	{morango: 0},
	{Moeda: 0},
	{GramaFullBorder: 0},
	{Âncora: 0},
	{Pontos: 0},
	{Vida1: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Vida2: 0},
	{Vida3: 0},
	{colision: 0},
	{Banco1: 0},
	{Árvore1: 0},
	{Pedra1: 0},
	{Pedra2: 0},
	{Caixa: 0},
	{Árvore2: 0},
	{Skate: 0},
	{Terra7: 0},
	{Árvore3: 0},
	{Sprite5: 0},
	{BotãoHistória: 0},
	{BotãoStart: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{BotãoVoltar: 0},
	{Texto: 0},
	{Sprite7: 0},
	{Barreira: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{Sprite8: 0},
	{Fonte: 0},
	{Arbusto1: 0},
	{Arbusto2: 0},
	{Arbusto3: 0},
	{Texto2: 0},
	{aviso: 0},
	{alerta: 0},
	{Sprite9: 0},
	{pessego: 0},
	{avisop: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Terra8: 0},
	{Terra9: 0},
	{Sprite15: 0},
	{Arbusto4: 0},
	{Pedra3: 0},
	{Pedra4: 0},
	{Sprite: 0},
	{Arbusto5: 0},
	{Toque: 0},
	{Vidas: 0},
	{pontos: 0},
	{numeroFase: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	slime: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Grama1_bordaesq: class extends self.ISpriteInstance {},
	Grama2_meio: class extends self.ISpriteInstance {},
	Grama3_bordadir: class extends self.ISpriteInstance {},
	Espinho: class extends self.ISpriteInstance {},
	Espinho2: class extends self.ISpriteInstance {},
	Grama_solo: class extends self.ISpriteInstance {},
	maca: class extends self.ISpriteInstance {},
	Inimigo_cogu: class extends self.ISpriteInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	Terra3: class extends self.ISpriteInstance {},
	Terra1: class extends self.ISpriteInstance {},
	Terra2: class extends self.ISpriteInstance {},
	Terra4: class extends self.ISpriteInstance {},
	Terra6: class extends self.ISpriteInstance {},
	Terra5: class extends self.ISpriteInstance {},
	FunfoGameOver: class extends self.ITiledBackgroundInstance {},
	Áudio: class extends self.IInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Árvore: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	BotaoTenNov: class extends self.ISpriteInstance {},
	BotaoTelaIni: class extends self.ISpriteInstance {},
	BotaoGameOver: class extends self.ISpriteInstance {},
	morango: class extends self.ISpriteInstance {},
	Moeda: class extends self.ISpriteInstance {},
	GramaFullBorder: class extends self.ISpriteInstance {},
	Pontos: class extends self.ITextInstance {},
	Vida1: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Vida2: class extends self.ISpriteInstance {},
	Vida3: class extends self.ISpriteInstance {},
	colision: class extends self.ISpriteInstance {},
	Banco1: class extends self.ISpriteInstance {},
	Árvore1: class extends self.ISpriteInstance {},
	Pedra1: class extends self.ISpriteInstance {},
	Pedra2: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Árvore2: class extends self.ISpriteInstance {},
	Skate: class extends self.ISpriteInstance {},
	Terra7: class extends self.ISpriteInstance {},
	Árvore3: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	BotãoHistória: class extends self.ISpriteInstance {},
	BotãoStart: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	BotãoVoltar: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Barreira: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Fonte: class extends self.ISpriteInstance {},
	Arbusto1: class extends self.ISpriteInstance {},
	Arbusto2: class extends self.ISpriteInstance {},
	Arbusto3: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	aviso: class extends self.ITextInstance {},
	alerta: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	pessego: class extends self.ISpriteInstance {},
	avisop: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Terra8: class extends self.ISpriteInstance {},
	Terra9: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Arbusto4: class extends self.ISpriteInstance {},
	Pedra3: class extends self.ISpriteInstance {},
	Pedra4: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Arbusto5: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {}
}